from server.schemas.user import UserSchema
from server.schemas.specie import SpecieSchema
from server.schemas.pet import PetSchema
from server.schemas.location import LocationSchema
from server.schemas.code import CodeSchema
from server.schemas.user_pet import UserPetSchema
from server.schemas.notification import NotificationSchema
from server.schemas.user_auth import UserAuthSchema
from server.schemas.pet_location import PetLocationSchema
from server.schemas.user_notification import UserNotificationSchema
from server.schemas.services import *