"""Deleted phone_validated on User

Revision ID: db4039dd743f
Revises: 8bafae4bb950
Create Date: 2023-12-03 04:59:20.335948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db4039dd743f'
down_revision = '8bafae4bb950'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'phone_verified')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
