name: 'Backend tests'

on:
  pull_request:
    branches: ['master']

jobs:
  builds:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v2
      - name: 'Setup Python'
        working-directory: ./backend
        uses: actions/install-python@v5
        with:
          python-version: '3.10'
      - name: 'Install dependencies'
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry config virtualenvs.create false
          poetry install
      - name: 'Run tests'
        working-directory: ./backend
        run: 'pytest --exitfirst'